#!/usr/bin/env bash

python -u bootstrap.py 1 > bootstrap.py.out.1
python -u bootstrap.py 2 > bootstrap.py.out.2
python -u bootstrap.py 3 > bootstrap.py.out.3
python -u bootstrap.py 4 > bootstrap.py.out.4
python -u bootstrap.py 5 > bootstrap.py.out.5
python -u bootstrap.py 6 > bootstrap.py.out.6
python -u bootstrap.py 7 > bootstrap.py.out.7
python -u bootstrap.py 8 > bootstrap.py.out.8
python -u bootstrap.py 9 > bootstrap.py.out.9
python -u bootstrap.py 10 > bootstrap.py.out.10
python -u bootstrap.py 11 > bootstrap.py.out.11
python -u bootstrap.py 12 > bootstrap.py.out.12
python -u bootstrap.py 13 > bootstrap.py.out.13
python -u bootstrap.py 14 > bootstrap.py.out.14
python -u bootstrap.py 15 > bootstrap.py.out.15
python -u bootstrap.py 16 > bootstrap.py.out.16
python -u bootstrap.py 17 > bootstrap.py.out.17
python -u bootstrap.py 18 > bootstrap.py.out.18
python -u bootstrap.py 19 > bootstrap.py.out.19
python -u bootstrap.py 20 > bootstrap.py.out.20
python -u bootstrap.py 21 > bootstrap.py.out.21
python -u bootstrap.py 22 > bootstrap.py.out.22
python -u bootstrap.py 23 > bootstrap.py.out.23
python -u bootstrap.py 24 > bootstrap.py.out.24
python -u bootstrap.py 25 > bootstrap.py.out.25
python -u bootstrap.py 26 > bootstrap.py.out.26
python -u bootstrap.py 27 > bootstrap.py.out.27
python -u bootstrap.py 28 > bootstrap.py.out.28
python -u bootstrap.py 29 > bootstrap.py.out.29
python -u bootstrap.py 30 > bootstrap.py.out.30
python -u bootstrap.py 31 > bootstrap.py.out.31
python -u bootstrap.py 32 > bootstrap.py.out.32
python -u bootstrap.py 33 > bootstrap.py.out.33
python -u bootstrap.py 34 > bootstrap.py.out.34
python -u bootstrap.py 35 > bootstrap.py.out.35
python -u bootstrap.py 36 > bootstrap.py.out.36
python -u bootstrap.py 37 > bootstrap.py.out.37
python -u bootstrap.py 38 > bootstrap.py.out.38
python -u bootstrap.py 39 > bootstrap.py.out.39
python -u bootstrap.py 40 > bootstrap.py.out.40
python -u bootstrap.py 41 > bootstrap.py.out.41
python -u bootstrap.py 42 > bootstrap.py.out.42
python -u bootstrap.py 43 > bootstrap.py.out.43
python -u bootstrap.py 44 > bootstrap.py.out.44
python -u bootstrap.py 45 > bootstrap.py.out.45
python -u bootstrap.py 46 > bootstrap.py.out.46
python -u bootstrap.py 47 > bootstrap.py.out.47
python -u bootstrap.py 48 > bootstrap.py.out.48
python -u bootstrap.py 49 > bootstrap.py.out.49
python -u bootstrap.py 50 > bootstrap.py.out.50
python -u bootstrap.py 51 > bootstrap.py.out.51
python -u bootstrap.py 52 > bootstrap.py.out.52
python -u bootstrap.py 53 > bootstrap.py.out.53
python -u bootstrap.py 54 > bootstrap.py.out.54
python -u bootstrap.py 55 > bootstrap.py.out.55
python -u bootstrap.py 56 > bootstrap.py.out.56
python -u bootstrap.py 57 > bootstrap.py.out.57
python -u bootstrap.py 58 > bootstrap.py.out.58
python -u bootstrap.py 59 > bootstrap.py.out.59
python -u bootstrap.py 60 > bootstrap.py.out.60
python -u bootstrap.py 61 > bootstrap.py.out.61
python -u bootstrap.py 62 > bootstrap.py.out.62
python -u bootstrap.py 63 > bootstrap.py.out.63
python -u bootstrap.py 64 > bootstrap.py.out.64
python -u bootstrap.py 65 > bootstrap.py.out.65
python -u bootstrap.py 66 > bootstrap.py.out.66
python -u bootstrap.py 67 > bootstrap.py.out.67
python -u bootstrap.py 68 > bootstrap.py.out.68
python -u bootstrap.py 69 > bootstrap.py.out.69
python -u bootstrap.py 70 > bootstrap.py.out.70
python -u bootstrap.py 71 > bootstrap.py.out.71
python -u bootstrap.py 72 > bootstrap.py.out.72
python -u bootstrap.py 73 > bootstrap.py.out.73
python -u bootstrap.py 74 > bootstrap.py.out.74
python -u bootstrap.py 75 > bootstrap.py.out.75
python -u bootstrap.py 76 > bootstrap.py.out.76
python -u bootstrap.py 77 > bootstrap.py.out.77
python -u bootstrap.py 78 > bootstrap.py.out.78
python -u bootstrap.py 79 > bootstrap.py.out.79
python -u bootstrap.py 80 > bootstrap.py.out.80
python -u bootstrap.py 81 > bootstrap.py.out.81
python -u bootstrap.py 82 > bootstrap.py.out.82
python -u bootstrap.py 83 > bootstrap.py.out.83
python -u bootstrap.py 84 > bootstrap.py.out.84
python -u bootstrap.py 85 > bootstrap.py.out.85
python -u bootstrap.py 86 > bootstrap.py.out.86
python -u bootstrap.py 87 > bootstrap.py.out.87
python -u bootstrap.py 88 > bootstrap.py.out.88
python -u bootstrap.py 89 > bootstrap.py.out.89
python -u bootstrap.py 90 > bootstrap.py.out.90
python -u bootstrap.py 91 > bootstrap.py.out.91
python -u bootstrap.py 92 > bootstrap.py.out.92
python -u bootstrap.py 93 > bootstrap.py.out.93
python -u bootstrap.py 94 > bootstrap.py.out.94
python -u bootstrap.py 95 > bootstrap.py.out.95
python -u bootstrap.py 96 > bootstrap.py.out.96
python -u bootstrap.py 97 > bootstrap.py.out.97
python -u bootstrap.py 98 > bootstrap.py.out.98
python -u bootstrap.py 99 > bootstrap.py.out.99
python -u bootstrap.py 100 > bootstrap.py.out.100

# nohup parallel -j 10 < run_bootstrap.sh &